version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    env_file:
      - .env.postgres.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
