# Generated by Django 5.1.2 on 2024-10-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stock_options_stock_name_stock_stocking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
