# Generated by Django 5.1.2 on 2024-10-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='from_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
