# Generated by Django 5.1.2 on 2024-10-30 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockmovement_from_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stocking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
